<?php
$data = array (
  366 => 
  array (
    'cat_id' => '366',
    'cat_name' => '国内研学',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '366',
    'name' => '国内研学',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '北京',
    'measure_unit' => '',
    'parent_id' => '366',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '375',
    'name' => '北京',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '上海',
    'measure_unit' => '',
    'parent_id' => '366',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '376',
    'name' => '上海',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '香港',
    'measure_unit' => '',
    'parent_id' => '366',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '377',
    'name' => '香港',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '国际研学',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '367',
    'name' => '国际研学',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '英国',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '381',
    'name' => '英国',
  ),
  382 => 
  array (
    'cat_id' => '382',
    'cat_name' => '法国',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '382',
    'name' => '法国',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '东南亚',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '379',
    'name' => '东南亚',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '380',
    'name' => '美国',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => '国防教育',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '387',
    'name' => '国防教育',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '自然地理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '384',
    'name' => '自然地理',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '素质拓展',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '388',
    'name' => '素质拓展',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '人文历史',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '385',
    'name' => '人文历史',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '职业体验',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '389',
    'name' => '职业体验',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '科技智能',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '386',
    'name' => '科技智能',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '研学宁波',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 0,
    'id' => '383',
    'name' => '研学宁波',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '家居、家具、家装、厨具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '家居、家具、家装、厨具',
  ),
  306 => 
  array (
    'cat_id' => '306',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '306',
    'name' => '家纺',
  ),
  307 => 
  array (
    'cat_id' => '307',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '307',
    'name' => '家具',
  ),
  308 => 
  array (
    'cat_id' => '308',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '308',
    'name' => '厨具',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '个护化妆、清洁用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '个护化妆、清洁用品',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '香水彩妆',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '香水彩妆',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '套装',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '香水',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '唇部',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '唇部',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '面部护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '109',
    'name' => '面部护肤',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '套装',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '清洁',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '清洁',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '护肤',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '面膜',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '洗发护发',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '套装',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '洗发',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '护发',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '酒类饮料',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => '酒水',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '276',
    'name' => '白酒',
  ),
  278 => 
  array (
    'cat_id' => '278',
    'cat_name' => '葡萄酒/果酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '278',
    'name' => '葡萄酒/果酒',
  ),
  281 => 
  array (
    'cat_id' => '281',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '281',
    'name' => '预调酒',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '272',
    'name' => '冲调饮品',
  ),
  282 => 
  array (
    'cat_id' => '282',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '282',
    'name' => '蜂蜜',
  ),
  283 => 
  array (
    'cat_id' => '283',
    'cat_name' => '成人奶粉',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '283',
    'name' => '成人奶粉',
  ),
  284 => 
  array (
    'cat_id' => '284',
    'cat_name' => '豆浆/豆奶粉',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '284',
    'name' => '豆浆/豆奶粉',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '饮料饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '273',
    'name' => '饮料饮品',
  ),
  290 => 
  array (
    'cat_id' => '290',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '290',
    'name' => '茶饮料',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '291',
    'name' => '碳酸饮料',
  ),
  292 => 
  array (
    'cat_id' => '292',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '292',
    'name' => '功能饮料',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '手机、数码、通信',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '手机、数码、通信',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '热卖手机',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '144',
    'name' => '热卖手机',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '华为荣耀',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => '华为荣耀',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '三星盖乐世',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '148',
    'name' => '三星盖乐世',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '联通4G',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '153',
    'name' => '联通4G',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'iPhone',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => 'iPhone',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '小米特供',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '小米特供',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '145',
    'name' => '手机配件',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '数码影音',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '146',
    'name' => '数码影音',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '食品、酒类、生鲜、特产',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '食品、酒类、生鲜、特产',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '进口水果',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '糖果巧克力',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '牛奶乳品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '牛奶乳品',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴、玩具乐器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '母婴、玩具乐器',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '223',
    'name' => '孕婴洗护',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '221',
    'name' => '孕婴奶粉',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '营养/辅食',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '222',
    'name' => '营养/辅食',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家用电器',
    'measure_unit' => '1111',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '255',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '家用电器',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '五金家装',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '182',
    'name' => '五金家装',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => '家具五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '218',
    'name' => '家具五金',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '179',
    'name' => '生活电器',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '180',
    'name' => '厨房电器',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '178',
    'name' => '大家电',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '男装、女装、内衣、珠宝',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '255',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '男装、女装、内衣、珠宝',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '女装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '女装馆',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '连衣裙',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '棉麻T恤',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '棉麻T恤',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '内衣馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '内衣馆',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '夏季睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '夏季睡衣',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '男装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '男装馆',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => 'POLO衫',
  ),
);
?>